site_name: Fastapi-Mailman
site_url: https://marktennyson.github.io/fastapi-mailman
repo_url: https://github.com/marktennyson/fastapi-mailman
repo_name: marktennyson/fastapi-mailman
dev_addr: localhost:8080
nav:
  - Tutorial: index.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
markdown_extensions:
  - pymdownx.highlight:
      linenums: false
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - fastapi_mailman
