site_name: Flask-Mailman
site_url: https://waynerv.github.io/flask-mailman
repo_url: https://github.com/waynerv/flask-mailman
repo_name: waynerv/flask-mailman
nav:
  - Tutorial: index.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
markdown_extensions:
  - pymdownx.highlight:
      linenums: false
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - flask-mailman
